apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 8081 # only for dev
      targetPort: 3000
  type: LoadBalancer